import { Movie } from './types';

export const seedMovies: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    year: 2010,
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    director: 'Christopher Nolan',
    actors: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
  },
  {
    id: '2',
    title: 'The Dark Knight',
    year: 2008,
    genres: ['Action', 'Crime', 'Drama'],
    director: 'Christopher Nolan',
    actors: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
  },
  {
    id: '3',
    title: 'Pulp Fiction',
    year: 1994,
    genres: ['Crime', 'Drama'],
    director: 'Quentin Tarantino',
    actors: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'],
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
  },
  {
    id: '4',
    title: 'Parasite',
    year: 2019,
    genres: ['Thriller', 'Drama'],
    director: 'Bong Joon-ho',
    actors: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    description: 'Greed and personal vendetta threaten the once peaceful coexistence of the rich and the poor in this black comedy thriller.',
  },
  {
    id: '5',
    title: 'Everything Everywhere All at Once',
    year: 2022,
    genres: ['Action', 'Adventure', 'Comedy'],
    director: 'Daniel Kwan, Daniel Scheinert',
    actors: ['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan'],
    description: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.',
  },
  {
    id: '6',
    title: 'The Matrix',
    year: 1999,
    genres: ['Action', 'Sci-Fi'],
    director: 'Lana Wachowski, Lilly Wachowski',
    actors: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    description: 'A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system of enslaving the human race.',
  },
  {
    id: '7',
    title: 'Interstellar',
    year: 2014,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    director: 'Christopher Nolan',
    actors: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
  },
  {
    id: '8',
    title: 'Dune: Part Two',
    year: 2024,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    director: 'Denis Villeneuve',
    actors: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against conspirators who destroyed his family.',
  },
  {
    id: '9',
    title: 'Oppenheimer',
    year: 2023,
    genres: ['Biography', 'Drama', 'History'],
    director: 'Christopher Nolan',
    actors: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon'],
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
  },
  {
    id: '10',
    title: 'La La Land',
    year: 2016,
    genres: ['Comedy', 'Drama', 'Music'],
    director: 'Damien Chazelle',
    actors: ['Ryan Gosling', 'Emma Stone', 'John Legend'],
    description: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
  },
  // Add more movies (total ~30)
  {
    id: '11',
    title: 'The Grand Budapest Hotel',
    year: 2014,
    genres: ['Comedy', 'Drama'],
    director: 'Wes Anderson',
    actors: ['Ralph Fiennes', 'F. Murray Abraham', 'Mathieu Amalric'],
    description: 'A concierge at a famous hotel in 1930s Europe becomes involved in a murder investigation.',
  },
  {
    id: '12',
    title: 'Mad Max: Fury Road',
    year: 2015,
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    director: 'George Miller',
    actors: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    description: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners and a drifter.',
  },
  {
    id: '13',
    title: 'Get Out',
    year: 2017,
    genres: ['Horror', 'Mystery', 'Thriller'],
    director: 'Jordan Peele',
    actors: ['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'],
    description: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
  },
  {
    id: '14',
    title: 'The Shawshank Redemption',
    year: 1994,
    genres: ['Drama'],
    director: 'Frank Darabont',
    actors: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'],
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
  },
  {
    id: '15',
    title: 'Spirited Away',
    year: 2001,
    genres: ['Animation', 'Adventure', 'Family'],
    director: 'Hayao Miyazaki',
    actors: ['Daveigh Chase', 'Suzanne Pleshette', 'Jason Marsden'],
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.',
  },
];

export const genresList = ['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Family', 'History', 'Horror', 'Music', 'Mystery', 'Sci-Fi', 'Thriller'];
